spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newreka?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: d103
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          import_files: 'classpath:static-data.sql'

jwt:
  secret:
    key: 'f0ndVYIvHHbeOXHrSHNDAE2h2LzyP/2NIYXcX21aLYA='
oauth:
  kakao:
    client_id: 6552fbe0384de4d45a21b5039929f363 # REST API 키
    redirect_uri: http://localhost:3000/oauth/redirected/kakao
    client_secret: gHrBPAOuAC0jrMXs2O2Lm9c6bsjPwZT9 # Client Secret 키
    scope: profile_nickname, account_email
#    scope: nickname, account_email