server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newreka?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #url: jdbc:mysql://43.202.33.232:3306/newreka?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

    username: d103
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        hbm2ddl:
          import_files: 'classpath:static-data.sql'
  mail:
    host: smtp.naver.com # 이메일 서버 주소를 적어주세요.
    port: 587 #465  # 포트 번호를 적어주세요.
    username: krbest98@naver.com # 이메일 계정의 사용자 이름을 적어주세요.
    password: newreka!! # 이메일 계정의 비밀번호를 적어주세요.
    properties:
      mail:
        smtp.auth:true
        smtp.starttls.enable:true

jwt:
  secret:
    key: 'f0ndVYIvHHbeOXHrSHNDAE2h2LzyP/2NIYXcX21aLYA='
oauth:
  kakao:
    client_id: 6552fbe0384de4d45a21b5039929f363 # REST API 키
    redirect_uri: http://localhost:3000/oauth/redirected/kakao
    client_secret: gHrBPAOuAC0jrMXs2O2Lm9c6bsjPwZT9 # Client Secret 키
    scope: profile_nickname, account_email
#    scope: nickname, account_email
